### PR TITLE
delete post's attachments

### PR DESCRIPTION
**Pull request by cmersinli**

### CODE REVIEW

**Comment by Dagefoerde** [comment]
Hi @ceremy1, thank you for your contribution. Could you please elaborate a bit as to what problem your patch is trying to solve, how you encountered it and how we can make sure that it does not exist anymore after applying this patch?

**Comment by ceremy1** [comment]
> Hi @ceremy1, thank you for your contribution. Could you please elaborate a bit as to what problem your patch is trying to solve, how you encountered it and how we can make sure that it does not exist anymore after applying this patch?
hi @Dagefoerde  ,
the orphan files were remains in the server When the post was deleted.At least, I think so.
i cant see  function which delete this orphan files

**Comment by ceremy1** [comment]
> Can you confirm that, with your patch, the files do not remain on the server anymore? That would be great. Also, when you have confirmed that, could you please look at the hints from the CI server and polish your fix a bit? https://travis-ci.org/learnweb/moodle-mod_moodleoverflow/jobs/484782669 There are a lot of warnings, feel free to skip these and focus on the ones marked as "Error" instead. Thank you!

hi @Dagefoerde ;
ofcourse i have confirmed. in fact you hace confirmed too. you write a discussion and attach a image this post. then you copied this image adress link . you will see still work this adress when you delete this post.

**Comment by Laur0r** [comment]
Hello @cmersinli,
I'm sorry for the late reply. Could you rebase your code so that it is up to date with the current versions? Thank you

**Pull request closed without merging**
